### ISSUE TITLE
Add wait time info to the UI

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#16]
@kntsoriano Once https://github.com/exercism/website/pull/660 is deployed and croned, the next step is to get it into the UI. This should be very simple

For now, I'd just like to change [this line](https://github.com/exercism/website/blob/master/app/views/my/solutions/_next_steps.html.haml#L10) so it says something like:

>  There are currently x solutions ahead of this in the Ruby queue, and y ahead in the High Scores queue. The median waiting time for mentoring on this exercise is `XYZ`.  Learn more about how mentor queues work.

Where `XYZ` is your saved wait_time and might be "19 days", "3 days", or "7 hours", or something.

If you could do this before the weekend, then we can get this deployed before I go on holiday, which would be very exciting :)

**Comment by kntsoriano** [comment]
@iHiD Where should we show the median wait time for tracks?

**Comment by iHiD** [comment]
That's going to go on the signup modals but I want to wait for Nic to design that, so we'll do it when I'm back :)
