### ISSUE TITLE
Add Pagerduty

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#20]
- Let's get Slack alerts about all the warning things.
- I want my phone ringing if the site goes offline.
- Can we alert Slack (and maybe a text message?) if we're getting nailed by a bot or DDOS'd so we can go and respond.

**Comment by kntsoriano** [comment]
Todos: 
- [x] Configure resilience checker via Cloudwatch and Opsgenie
- [x] Configure diskspace checker via Cloudwatch and Opsgenie
- [x] Configure alert webhook via AWS Lambda, SNS, and Opsgenie
- [x] Configue Slack integration with alert webhook

@ccare Could you check if these are correct and if I have missed anything?

**Comment by ccare** [comment]
looks good for starters, I'd leave the freshping to last, it's returning a lot of false positives atm and I'm wondering about it.

Working out a good deployment for the webhook lambda would be awesome if you want something fun and isolated to look at. I just hacked it on kaido.

**Comment by iHiD** [comment]
Where are we with this? How do we move forward?

**Comment by kntsoriano** [comment]
I haven't done anything on this yet. I'll be doing this before working on the Changelog.

**Comment by iHiD** [comment]
OK, great! :)
