### ISSUE TITLE
Add line about what happens when we delete an account to T&Cs

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#24]
The T&Cs file is [here](https://github.com/exercism/website-copy/blob/master/pages/terms_of_service.md).

**Comment by iHiD** [comment]
@ccare Did I see that you did this?

**Comment by ccare** [comment]
It's here - https://github.com/exercism/website-copy/pull/1232 - I'm not sure whether we're still happy with this. Can merge if so.

**Comment by iHiD** [comment]
Great. Merged. Thanks :)
