### ISSUE TITLE
Add "About Exercism" page

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#26]

**Comment by nicolechalmers** [comment]
Designs for feedback:

<img width="601" alt="Screen Shot 2019-08-08 at 10 43 07" src="https://user-images.githubusercontent.com/5421823/62692900-670d4a00-b9c9-11e9-9902-1889701224ec.png">
<img width="582" alt="Screen Shot 2019-08-08 at 10 43 12" src="https://user-images.githubusercontent.com/5421823/62692901-670d4a00-b9c9-11e9-87f8-c2848f406c48.png">
<img width="580" alt="Screen Shot 2019-08-08 at 10 43 15" src="https://user-images.githubusercontent.com/5421823/62692902-670d4a00-b9c9-11e9-841c-5c16a7d90932.png">

**Comment by iHiD** [comment]
We did this and it looks lovely :)
