### ISSUE TITLE
Don't let people become mentors unless they've submitted a solution.

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#33]
Don't let people become mentors unless they've posted a solution.

Following on from #32, to stop people becoming mentors for spam purposes, let's stop someone becoming a mentor unless they've posted a solution.

The various checks are:

- [x] Don't show "Mentor dashboard" link in the menu.
- [x] Fail in `Mentor::RegistrationsController#create`

**Comment by kntsoriano** [comment]
@iHiD I checked through the database and 25% of our mentors haven't submitted a solution. If we push through with this change, they won't be able to see they won't be access the mentor dashboard. I'll just do the third thing on the list first and wait for what you think.

I'm not sure if I queried the data correctly :)

**Comment by iHiD** [comment]
That's useful, thanks. And really nice work for checking! I'll dig into the data some more tomorrow and then update this issue.

**Comment by kntsoriano** [comment]
@iHiD Any news on this? Thanks.

**Comment by iHiD** [comment]
There are 161 people who have mentored but never submitted something themselves. They have mentored 1783 solutions between them. 5 of them have been active in the last week.

So I think these below make sense. Do you agree?

---

>  Don't show "Mentor dashboard" link in the menu.

Let's do this for people who are **not mentors** and **have no solutions**

> MentorController#restrict_to_mentors!

Let's not do this for now.
