### ISSUE TITLE
Recaptcha not working to stop bots

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#37]
- [ ] From reading the docs, we should include Recaptcha on all external pages to help it observe behaviour. So I think when someone is not logged in, we should add it.

- [ ] The following are all users that have spammed us: `332949, 332962, 333064, 333475, 334739, 335444, 336003, 336635, 336659, 338889, 340063, 341348, 341380` - could you  see if there is a reason recaptcha didn't work, what their scores were, etc

**Comment by iHiD** [comment]
@kntsoriano Also, I wonder if we should just stick to recaptcha 2?

**Comment by iHiD** [comment]
Example spam here btw: https://exercism.io/tracks/lua/exercises/bowling/solutions/f3c8b76f976b4d8b821e037ffc9f278d

(I'll leave it there for the next day for you to see)

**Comment by ccare** [comment]
It might be worth considering whether using the recapture v2 would be more aligned to our values too (less tracking, maybe).

**Comment by iHiD** [comment]
Yeah. Agreed. OK - @kntsoriano if it's simple enough, could we just switch to v2 for now please? And then come back to v3 when we've thought about it some more. Sorry to have made you do unnecessary work!

**Comment by kntsoriano** [comment]
@iHiD No problem man :) Our recaptcha v3 stats also indicate a low rate of suspicious requests (less than 1%), so it would really mean adding it to the entire site in order for it to be effective. I'll revert back to recaptcha V2.

**Comment by iHiD** [comment]
Brilliant. Great work! :)
