### ISSUE TITLE
Profile image fallback

### ISSUE THREAD

**Issue by nicolechalmers** [exercism/wip#42]
Some of the mentor profile images aren't showing. I wondered if we can fix this and also if we already have a fallback for broken images or if I should design one?

https://exercism.io/team/mentors :
<img width="1280" alt="Screen Shot 2019-10-03 at 16 17 09" src="https://user-images.githubusercontent.com/5421823/66134895-5bb95200-e5f9-11e9-9476-f6988c7ce727.png">

**Comment by iHiD** [comment]
@kntsoriano I think [this commit](https://github.com/exercism/website/commit/85f806a2448e674290a5e5de41deac769b260eaf#diff-9baeef12b7e595e816073c9fd0118f6b) is how we best do this. Its a useful technique if you weren't aware of it. We might want an actual link to an image though so we don't make the page huge by embedding lots of base64

**Comment by kntsoriano** [comment]
@nicolechalmers Really depends on how you want it, we can do a white square just how @iHiD suggested, but we can also do a fallback image specifically created for mentors. I'll do the white square for now, just to make it look decent.

**Comment by kntsoriano** [comment]
@nicolechalmers We already have a fallback, it's this image: 
![anonymous](https://user-images.githubusercontent.com/1901520/66203676-85e34080-e6db-11e9-99af-61939604874d.png)

**Comment by iHiD** [comment]
Sweet. So @kntsoriano use the onerror with that image and we're sorted I think :)
