### ISSUE TITLE
Add tweet status to changelog admin

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#45]
@kntsoriano Can you push [this](https://github.com/exercism/website/blob/master/app/controllers/changelog_admin/entries_controller.rb#L40) through DJ pls?

**Comment by kntsoriano** [comment]
@iHiD So that code taps this model: https://github.com/exercism/website/blob/master/app/models/twitter_account.rb/. This model pushes it to DJ.

**Comment by iHiD** [comment]
So, the problem here is that if the Twitter credentials are missing, the publishing action blows up, even though the publish phase of it completes correctly. So I wondered if that bit should get to DJ earlier? Alternatively, I wonder if we should catch an error if `tweet!` explodes and warn the user that it's failed, rather than just 500ing?

This might be an issue because we'll always have credentials of course, so you might just think I'm worrying unnecessarily :)

**Comment by kntsoriano** [comment]
~~Sure. We could do this. I misinterpreted that the tweet was just a way to get things out and it wasn't a crucial step in the publishing process. I thought that we could still publish the article, and when the tweet fails, DJ will rerun it.~~

~~So this means that a tweet will go out first before we publish? There might be a very small window that the link is dead after the tweet is published, but I guess it would happens too fast for people to actually click the dead link.~~

~~I'll be renaming the issue to reflect this change.~~

**EDIT:**

I think we should still push through with publishing the article even if the tweet fails. It feels like we're depending too much on Twitter if we don't.

I will add a status indicator on the dashboard to show whether the tweet was sent or not. As most of our errors would come from Twitter crashing, I'll hold off on adding a button to resend the tweet as DJ has its own retry logic.
