### ISSUE TITLE
Ensure Ruby 2.6.3 everywhere

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#50]
@kntsoriano Can you check that we're using 2.6.3 everywhere pls? Like servers and travis on website etc?

**Comment by kntsoriano** [comment]
So Travis uses the `ruby-version` file and we've set it to 2.6.3 on the PR. I've also opened a PR in our chef scripts to update our webservers to ruby 2.6.3. Anything else I missed?

**Comment by iHiD** [comment]
Thanks dude.
