### ISSUE TITLE
Remove hard-coded repo name

### ISSUE THREAD

**Issue by iHiD** [exercism/wip#60]
<img width="815" alt="Screenshot 2019-12-11 at 17 49 20" src="https://user-images.githubusercontent.com/286476/70606015-f8721e80-1c3e-11ea-819c-46d89f2910a6.png">

**Comment by kntsoriano** [comment]
Thanks. I've updated `backlog`, `bugs`, `ideas`, and `support`.

**Comment by iHiD** [comment]
Thanks :)
