### ISSUE TITLE
Update Prismjs library.

### ISSUE THREAD

**Issue by neenjaw** [exercism/wip#62]
Hi,

I recently noticed a highlighting syntax error related to how Prismjs was highlight elixir and raised an issue -- see PrismJS/prism#2181.  It has since been patched and merged into the master, with the change now being reflected on [the test page](https://prismjs.com/test.html#language=elixir).

As requested by @ihid, this issue is to check if prism needs to be bumped to newest version.

**Comment by iHiD** [comment]
@kntsoriano This should be a quick one if you get 10mins pls.

**Comment by kntsoriano** [comment]
@iHiD The PR was just merged and hasn't been included in the CDN release yet.

On another note, I noticed that the latest version hosted on the CDN is 1.17.1 and the latest version on NPM is already at 1.19. Should we move away from the CDN, and just host it ourselves? We already have webpacker set up.

**Comment by iHiD** [comment]
If you think that's wisest, then sure :)
